{% set version = "0.53.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-matrixstats
  version: {{ version|replace("-", "_") }}

source:
  fn: matrixStats_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/matrixStats_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/matrixStats/matrixStats_{{ version }}.tar.gz
  sha256: df70bc9fb64716a7a633b5d0c2a2422b2c8d93ac5e64574528a325505df9712e

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('matrixStats')"  # [not win]
    - "\"%R%\" -e \"library('matrixStats')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/matrixStats
  license: Artistic-2.0
  summary: High-performing functions operating on rows and columns of matrices, e.g. col / rowMedians(),
    col / rowRanks(), and col / rowSds().  Functions optimized per data type and for
    subsetted calculations such that both memory usage and processing time is minimized.  There
    are also optimized vector-based methods, e.g. binMeans(), madDiff() and weightedMedian().
  license_family: OTHER

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
