travis:
  secure:
    BINSTAR_TOKEN: DdU3gOIxq2PQ0ZuPrhjmumCkvdbHWdV4NbdDaF8Vihi4LTqk1dI/AuitZhlW44IE7ZDtxSE9BNiW1wZTnTQ5iJNeZIu7m5TkDE2QwHMtekYnRfn4wBZsZJoW/sNRcEpbfRrwBU//vqBAk/jlI4MLQHTF7Z61pc6sf3JYYR7ir4u/s2JQb+UUewwX/9WmoP+pB/OZIdwiKUjVcOBJUoOatWXkP7d3qgnX4uqntpE5qeEY8d8c5U/C4VK43/8XUd0HVkkhjCIht29+Sqa6+54zPrUPfwKta+ctfXSI0YMrKjQvjDA665EmOPOxgv6O+aF3okikFD+Spqj5Iw2Tjg8vlLzGsR3547pK7jgmOtxbeQh3kNse7jgVJJzfaKTJ9gr0sLJx6aTdx7mqJCfAoXgTOplEdmQTDun3qslcctzypqTNqXOFIn3q/gf9KQBIVgustfLPnjfHKo/SnueO6Ncnc0My2AT3Lrg302xFQiyUZ4Gv7e7icD9OpRlGYSCZ3vLtMzFDlq3/EUTsHG9SAAyufHiiOz5D07nFRiOlgK58e7NhMiglpkyBwOT6sf/FgLvi0iRTEy4Br6D9EhBi8Q4E9KoiVcfdVMXN2ral05n7Ku7MUHMxIs+uFlXrAqjquYB/OYxBSKdLdul5J2PONrq3QTB+I/WypFzvw76Exy7HItg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
