travis:
  secure:
    BINSTAR_TOKEN: UBEargXn7sgKcV4sX62nqcNu96k2BRpggXxhGcaY5ipMzRynjc5WsmMpaWhpWYfsCs7ie1cxfvv+vzqMzblP50anSFPamMx6kLeK4oT/XBCnsY7Gkiv6QKepy3opd3JhC2BxmYxWA+9Wr44W9A+c/yiouH8mHckr/C6Uk+3HF5ncfkmUc2mbc+SsQlAVB7ICTZHX3Ts0/yU9uh1Hf/RIreLoRo6Jlw+CmsH07L25Hw8SDKQ4fSAXuKIr4wdmTvz9t6r4cFPXtoLaeO+S6LNh1i2CWo1lr2F2RDbgofUj5O0PzTGQ9pMzPPpeDqwKsfHeHD+pVtde3c20vl/VBBUwAxaPe7cJsuiNe4rx2NHTYd/xZEXShLG/i2VMZk3DM39CrK5wOtbQQ65d5eByCD51J+BZGQ/VvMGwBG11umwNJtCrBFaYJeuTkcUDJiSId3rdadKKk2q36N5LDDp1KuHE5SScS2wNfzWlvfU0aZYr6AvUql9h+3ID93QfKaQ3feJhlSCBBr6uwK8QlPKedYnzFHh0ggvA//X73jHktiTzj362fKJ1W4ERFQeFq3lcZHGFTphrsWP/sjtWvWxSk0HvmX+mt2fTHwvms7TwfHZO7gltIeOkOuUf9Ktvn+l3JDpH9dxPgMpaEvQ5jo44gFC9JUqpYN8lj0uJZW2AUQZ9S/4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
