appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qYjzTFEfhbmOI3bZdMWCsjjv2/mAGgq5D1f4pj0liiLE9D6frKzZ0wMWbkemAhjLkaf0oxT4wdTzwKHM442zyzEfwoOwDH9rEgmAHQ8JSXvgELjweuifdtCMZccY0ta8S5h2FA2CqQvZsHfd3UKGlDb9fr04ZP8rDBCt2Oq6jtanefQguC6/IIj4fp99MR7EA9OwJVZjsjqFPJy88Q0EkTSA+H+rTqZ3Ub8xobNklfkHIRazlHkLGSpqp8dngtvAJAkxPNto8qsOT+8xYwXRqiPMdK2PXN7wQy6/14aler81vcJFeVf6c+lx0GxQ8WmnvEk/igM99qCfIL0ZfrosWYwOL39HHM55JIYlTOjOvKQnY/lfNV6ammz+/j9/DrsI0GbDBWJW1BgQ00bufynCD9BrBcfyPjXCXHMwqoHgIos6GCnZSQyhH8BId13Di09mT0lHV4kt35lPMzOrDroMocUhGenpM7vUQxdgM8ao7YrGlJb05Xgsy/6LdiG8ieNXav4iZK1j6MKWGvUfQ6OfZIImOn940Bvvk3IWTpjzvKjd2LJ/F5BMY7fA76YVuOwfaMo3iDdGUPOMmKc7jQuMJ5btmgK2ZFT3CWcSMcKrSVXlDJYp/p8eEUuPvGX4Uwuk9MiuoRc+pzxwoq6Gd+thcx5c7K4Pf3GxUtWJzj7ixmg=}
