travis:
  secure:
    BINSTAR_TOKEN: o/DN7ffTgy5mA9Jc6mSa6kQ84FsE59mCQOzXbKciqPBYXv7jIz9knOnNxdn3kaXipjZMn7NRFXKf5uCtYdmp8yikItkj0l0sW9TAF0Zrdj0u43pC7KoLC9D2BZ9dWXpBA2Nymaj2MCljkb+ybAT9ge7BoMLYebCLkPQYAiIKxN77EN0UeO9qQ6O/Ttdx21DHG6PXwMZ12sNaZm6NlMh/8G6zkULuaqbsp+7nHvp6Ii46g3Wgwnz5BM2Vm2DOXoBnLa7jUm/hutWXtu0OTNe0Jsn8QYpfi4jXyFmZdqhPDAsDmnfD3YayLigXO3gQC4VjUpQpYMnLkVrLFumU3Bt1vvO1rd7zEWGa/xOC7YfxI45VxtA6d0CojHBfSjJfcmBhW169TSpiQi7pJg4bTdD3kAi+zPzOoEhz0BejHxK+xNx2musWkajsBb0UTi90uQpFB97e1LIMFpwjUt529w1+DM9cAInsOmGu9Y+JQiIigA08vEm1N2Be+P8TEFm/Qe4nFSOtCBxONW++flrCcUP0NotL2vCmHLUQNxtbXj9vnMrvW5AriBakDr9o2CHSYeLgqvMrIlOgE8zPnCqhhl5/XOYtI+9Ct9fkqdlupGUAtlYP+00474qiFArPnqX1CgTtoCivDy/e9nSY/E+xgM9CRuMANja9cIuQiULCusu5YJg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
